### PR TITLE
use explicit i18n versions again

### PR DESCRIPTION
**Pull request by ann-kilzer**
~~Let's see if this prevents the issue Russ was complaining about. Please check the netlify build~~

While this might not fix Russ's issue, I've bumped the i18n versions so we should have better translations

### CODE REVIEW

**Comment by ermish** [comment]
Still seeing only partial translations. 

image

**Comment by ermish** [comment]
also checked build....it says there's a yarn cache log, but it doesn't say what was cached or if anything new was pulled. 😞

**Comment by ann-kilzer** [comment]
I'm wondering if it's better to stick with numbered versions, at least until we figure out a way to get Netlify to automatically check for new packages / versions of Master. It's one more step, but at least it's explicit.

**Review by ermish — APPROVED** [review]
Either way is fine by me. Explicit is always easy to understand.

**Comment by ann-kilzer** [comment]
Not sure why the deploy is failing... need to look into it later

**Pull request merged**
