### PR TITLE
129 netlify 404 page

### LINKED ISSUE #129: Netlify 404 page
Use our own 404 page instead of the Netlify one

For example, https://www.findadoc.jp/bees goes to the Netlify page

### PR DESCRIPTION
**Pull request by claudiofreitas**
### How to test

Access any non-existing page.
Eg.: <domain>/non-existing-endpoint

### Screenshots

Right now it's a empty page with a dummy text:
image

### CODE REVIEW

**Comment by claudiofreitas** [comment]
Hi guys, can someone take a look and instruct me on what exactly to display in the 404 page?
Also if there is any change I need to do in the code as well.

The deploy of the current branch can be visualized here:
https://peaceful-chandrasekhar-3eb8f9.netlify.app/mitsukaranai

**Comment by ann-kilzer** [comment]
Hi! The current page set up in localhost for errors is `layouts/error.vue`. Can you connect that to Netlify's 404?

**Comment by claudiofreitas** [comment]
Hi Ann!
Sure, I will take a look at this as soon as I have some time :)

**Comment by ermish** [comment]
hey @claudiofreitas! any updates on this PR?

**Comment by theyokohamalife** [comment]
Closing this for now since the site will be redesigned soon!

**Pull request closed without merging**
