### PR TITLE
extract css for build

### LINKED ISSUE #61: Split css from html 🔗
The css is currently inlined in the html. 

We should split this out so it can be cached on the client side.

### PR DESCRIPTION
**Pull request by mdboop**
## Resolves #61

Extract CSS into a separate asset.

### How to test

No tests, config change.

### Screenshots

No screenshots for this.

### CODE REVIEW

**Comment by Ermish** [comment]
@mdboop we should get this css fix merged in sooner than later to reap the benefits!

**Comment by mdboop** [comment]
@Ermish and @theyokohamalife I was hesitant to add this because it was hurting performance, but I see the performance score has already degraded over the weekend from other changes (or maybe just noise in the lighthouse report... not sure).

In any case, we could merge this, and I'd suggest adding `target: "static"` back in and just fixing forward. As long as things are working, a little jank isn't the worst thing.

**Comment by Ermish** [comment]
> @Ermish and @theyokohamalife I was hesitant to add this because it was hurting performance, but I see the performance score has already degraded over the weekend from other changes (or maybe just noise in the lighthouse report... not sure).
> 
> In any case, we could merge this, and I'd suggest adding `target: "static"` back in and just fixing forward. As long as things are working, a little jank isn't the worst thing.

@mdboop sounds good! I created a separate issue #99 for when we switch to `static` mode

**Review by renderf0x — APPROVED** [review]
LGTM. This is inline (ha, no pun intended) with [official best practices for Vue](https://ssr.vuejs.org/guide/css.html#enabling-css-extraction) as well; great step.

**Review by Ermish — APPROVED** [review]
looks good for now! We can do further optimizations in future PRs.

**Review by theyokohamalife — APPROVED** [review]
LGTM if you're sure it doesn't impact performance. Please feel free to merge!

**Pull request merged**
