### PR TITLE
Bugfix/fix menu translation

### LINKED ISSUE #115: Use i18n for the menu
The menu hard-coded in English.

We need to : 
- Change the menu text to use i18n
- Add the Logout key:value in the localization project

### PR DESCRIPTION
**Pull request by JohnTitor2036**
### Screenshots

English
image

French
image

### CODE REVIEW

**Review by ann-kilzer — COMMENTED** [review]
Thanks for catching these. I thought we were having trouble with i18n in the script due to #31 but perhaps that's unique to the validations.

One requested addition and I'll update the submodule for you

**Comment by ann-kilzer** [comment]
I think I made a mistake in the merge 😢 . Sorry... could someone please fix?

**Review by ann-kilzer — APPROVED** [review]
LGTM ✌🏻

**Review by theyokohamalife — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
