### PR TITLE
Usage of i18n for the voucher status

### PR DESCRIPTION
**Pull request by JohnTitor2036**
### Screenshots

English
image

French
image

### CODE REVIEW

**Review by Ermish — APPROVED** [review]
LGTM.
'was there an issue this resolves?

**Comment by JohnTitor2036** [comment]
No, it was not link to any issue. @Ermish

**Comment by ann-kilzer** [comment]
I approved the PR in the submodule. Feel free to update the submodule to the lastest `main` in this branch, or I can do it later.

**Comment by JohnTitor2036** [comment]
I've updated the submodule in this branch ^^

**Comment by ann-kilzer** [comment]
Can you try again? That doesn't seem to be the latest main.

```sh
cd i18n
git checkout main
git pull
cd ..
git add i18n
git commit -m "bump submodule"
git push
```

**Comment by JohnTitor2036** [comment]
Here you go! It's my first time working with submodules, so I'm learning on the spot, but now I understand. Thanks!

**Comment by ann-kilzer** [comment]
Yes they are a little delicate, we are working on improving the process. Thanks for your patience

**Review by ann-kilzer — APPROVED** [review]
LGTM

**Pull request merged**
